# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workflows:
  IPS-Documentation:
    jobs:
      - envs
      - test:
          requires:
            - envs
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

version: 2.1
jobs:
  envs:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            virtualenv envs
            source ./envs/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./envs
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - persist_to_workspace:
          root: ~/repo
          paths: 
            - envs

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - run:
          name: Test Environment
          command: |
            pwd
            source ./envs/bin/activate
            pip freeze

  deploy:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - run:
          name: Convert ipynb to Markdown
          command: |
            pwd
            pip list

      - run:
          name: Remove all ipynb files
          command: |
            source ./envs/bin/activate
            git config user.name
            git config user.email
            git commit -m "convert ipynb"
            git push -u origin --all

      - run:
          name: Push back to Github
          command: |
            source ./envs/bin/activate
            git config user.name
            git config user.email
            git commit -m "convert ipynb"
            git push -u origin --all