# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workflows:
  IPS-Documentation:
    jobs:
      - envs
      - test:
          requires:
            - envs
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

version: 2.1
jobs:
  envs:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            virtualenv ~/tmp/envs
            source ~tmp/envs/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ~/tmp/envs
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - persist_to_workspace:
          root: ~/
          paths: 
            - tmp/envs

  test:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/tmp/

      - run:
          name: Test Environment
          command: |
            pwd
            source ~/tmp/envs/bin/activate
            pip freeze

  deploy:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/tmp/

      - checkout

      - run:
          name: Activate Environment
          command: |
            source ./envs/bin/activate

      - run:
          name: Convert ipynb to Markdown
          command: |
            bash ./scripts/convert-ipynb-to-md.sh
      
      - run:
          name: Remove ipynb
          command: |
            bash ./scripts/remove-ipynb.sh

      - run:
          name: Push back to Github
          command: |
            git config user.name "$gitUser"
            git config user.email "$gitEmail"
            git add .
            git add -u
            git commit -m "convert ipynb to markdown"
            git push -u origin --all